-   repo: https://github.com/pre-commit/pre-commit-hooks
    sha: 5bf6c09bfa1297d3692cadd621ef95f1284e33c0
    hooks:
    -   id: autopep8-wrapper
        stages:
        - commit
        - push
    -   id: check-docstring-first
        stages:
        - commit
        - push
    -   id: check-merge-conflict
        stages:
        - push
    -   id: double-quote-string-fixer
        stages:
        - commit
        - push
    -   id: fix-encoding-pragma
        stages:
        - commit
        - push
    -   id: flake8
        stages:
        - commit
        - push
